### ISSUE TITLE
"Invalid syntax" error with the ES server IP address...

### ISSUE THREAD

**Issue by relink2013** [yellowspaced/tubearchivist-metadata-export#1]
I assume the line that reads;

```
### Set your server!
es = Elasticsearch()
```

should be setup using the ip address of the ES server like; 

```
### Set your server!
es = Elasticsearch(172.18.0.10:9200)
```

but when I try to run the script I get a syntax error;

```
es = Elasticsearch(172.18.0.10:9200)
                         ^
SyntaxError: invalid syntax
```

**Comment by yellowspaced** [comment]
I'll update the inline comments to give an example when i get a chance.

It would be in full form, ['http://<username>:<password>@<server>:<port>']

Example
username: elastic
password: password
server: 192.168.0.10
port:9200

(['http://elastic:password@192.168.0.10:9200'])

**Comment by yellowspaced** [comment]
update in line comments in code.
